name: tree_service

services:
  webapp:
    build: ./webapp
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - webapp_data:/var/www/html/data:rw
    networks:
      - frontend
      - backend

  db:
    image: mysql:lts
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql:rw
    environment:
      - MYSQL_DATABASE=prod
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=webtrees
      - MYSQL_PASSWORD=password
    networks:
      - backend
  
  proxy:
    image: nginx:stable
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - webapp
    networks:
      - frontend
    ports:
      - 80:80


volumes:
  webapp_data: {}
  db_data: {}

networks:
  frontend: {}
  backend:
    internal: true