events {}

http {
  server {
    listen 443 ssl;

    server_name         zylocal.com;
    ssl_certificate     zylocal.com.pem;
    ssl_certificate_key zylocal.com.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    auth_basic            "Restricted Access";
    auth_basic_user_file  /etc/nginx/.htpasswd;

    root  /var/www/html;
    index index.php;

    location / {
      try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
      include       fastcgi_params;
      fastcgi_pass  webapp:9000;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      fastcgi_param HTTPS on;
    }
  }
}
